# Generated by Django 5.2.4 on 2025-07-27 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64)),
                ('category_name_en', models.CharField(max_length=64, null=True)),
                ('category_name_ru', models.CharField(max_length=64, null=True)),
                ('image', models.ImageField(upload_to='category_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Domik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('title_en', models.CharField(max_length=180, null=True)),
                ('title_ru', models.CharField(max_length=180, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('title_en', models.CharField(max_length=64, null=True)),
                ('title_ru', models.CharField(max_length=64, null=True)),
                ('bathroom', models.PositiveSmallIntegerField(default=0)),
                ('bathrooms_place', models.PositiveSmallIntegerField(default=0)),
                ('entry', models.PositiveSmallIntegerField()),
                ('departure', models.PositiveSmallIntegerField()),
                ('table_tennis', models.BooleanField(default=False)),
                ('bath_house', models.BooleanField(default=False)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('sauna', models.BooleanField(default=False)),
                ('air_hockey', models.BooleanField(default=False)),
                ('bathhouse_without_brooms', models.BooleanField(default=False)),
                ('billiards', models.BooleanField(default=False)),
                ('video', models.URLField()),
                ('check_in_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('type_of_housing', models.CharField(max_length=64)),
                ('type_of_housing_en', models.CharField(max_length=64, null=True)),
                ('type_of_housing_ru', models.CharField(max_length=64, null=True)),
                ('address', models.CharField(max_length=200)),
                ('address_en', models.CharField(max_length=200, null=True)),
                ('address_ru', models.CharField(max_length=200, null=True)),
                ('floor', models.CharField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('area', models.PositiveSmallIntegerField()),
                ('plot', models.PositiveSmallIntegerField()),
                ('count_people', models.PositiveSmallIntegerField(default=1)),
                ('weekdays_title', models.CharField(max_length=24)),
                ('weekdays_title_en', models.CharField(max_length=24, null=True)),
                ('weekdays_title_ru', models.CharField(max_length=24, null=True)),
                ('weekdays_price', models.PositiveIntegerField()),
                ('saturday_title', models.CharField(max_length=24)),
                ('saturday_title_en', models.CharField(max_length=24, null=True)),
                ('saturday_title_ru', models.CharField(max_length=24, null=True)),
                ('saturday_price', models.PositiveIntegerField()),
                ('friday_title', models.CharField(max_length=24)),
                ('friday_title_en', models.CharField(max_length=24, null=True)),
                ('friday_title_ru', models.CharField(max_length=24, null=True)),
                ('friday_price', models.PositiveIntegerField()),
                ('sunday_title', models.CharField(max_length=24)),
                ('sunday_title_en', models.CharField(max_length=24, null=True)),
                ('sunday_title_ru', models.CharField(max_length=24, null=True)),
                ('sunday_price', models.PositiveIntegerField()),
                ('pledge_title', models.CharField(max_length=24)),
                ('pledge_title_en', models.CharField(max_length=24, null=True)),
                ('pledge_title_ru', models.CharField(max_length=24, null=True)),
                ('pledge_price', models.PositiveIntegerField()),
                ('weekends_title', models.CharField(max_length=200)),
                ('weekends_title_en', models.CharField(max_length=200, null=True)),
                ('weekends_title_ru', models.CharField(max_length=200, null=True)),
                ('weekends_price', models.PositiveIntegerField()),
                ('new_year_title', models.CharField(max_length=200)),
                ('new_year_title_en', models.CharField(max_length=200, null=True)),
                ('new_year_title_ru', models.CharField(max_length=200, null=True)),
                ('new_year_price', models.PositiveIntegerField()),
                ('party_title', models.CharField(max_length=200)),
                ('party_title_en', models.CharField(max_length=200, null=True)),
                ('party_title_ru', models.CharField(max_length=200, null=True)),
                ('party_price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('additional_fees', models.TextField()),
                ('additional_fees_en', models.TextField(null=True)),
                ('additional_fees_ru', models.TextField(null=True)),
                ('important_information', models.TextField()),
                ('important_information_en', models.TextField(null=True)),
                ('important_information_ru', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_score', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house_image/')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_images', to='domik_app.house')),
            ],
        ),
    ]
