# Generated by Django 5.2.4 on 2025-07-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domik_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='floor',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, max_length=1),
        ),
    ]
