# Generated by Django 5.2.4 on 2025-07-28 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domik_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritehouse',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_houses', to='domik_app.house'),
        ),
        migrations.AlterField(
            model_name='review',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_review', to='domik_app.house'),
        ),
    ]
