# Generated by Django 5.2.4 on 2025-07-27 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domik_app', '0003_alter_house_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='domik_app.house'),
            preserve_default=False,
        ),
    ]
